---
site:
  title: "LB2298: Modernizing Virtualization with Red Hat OpenShift Virtualization and IBM Fusion: A Hands-On Lab"
  start_page: modules::index.adoc

content:
  sources:
  - url: .
    start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/v2.0.2/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ./content/supplemental-ui
  - path: ./content/lib
  - path: ui.yml
    contents: "static_files: [ .nojekyll, css/site-extra.css, js/buttons.js ]"

antora:
  extensions:
  - '@sntke/antora-mermaid-extension'
  - require: ./content/lib/dev-mode.js
    enabled: false
  - require: ./content/lib/inject-buttons.js

runtime:
  fetch: true

output:
  dir: ./www
